# Generated by Django 6.0 on 2025-12-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mark', models.IntegerField()),
                ('place', models.TextField(max_length=250)),
            ],
        ),
    ]
