# Generated by Django 6.0 on 2025-12-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
