# Generated by Django 6.0 on 2025-12-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0003_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('genere', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
