# Generated by Django 6.0 on 2025-12-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapchat', '0004_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('field', models.CharField(max_length=250)),
                ('mobile', models.IntegerField()),
                ('image', models.FileField(upload_to='images/')),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
