# Generated by Django 6.0 on 2025-12-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='place',
        ),
    ]
