# Generated by Django 6.0 on 2025-12-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_rename_price_product_mark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('image', models.FileField(upload_to='images/')),
                ('address', models.TextField(max_length=250)),
            ],
        ),
    ]
